spring:
  application:
    name: order-service
#server:#  port: 8201
eureka: 
  client: 
    service‚Äêurl: 
      defaultZone: http://eureka1:2001/eureka
   
feign:  hystrix:    enabled: true
   
management:  endpoints:    web:      exposure:        include: hystrix.stream
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 2000

---
spring:  profiles: order1
  
server:  port: 8201
---
spring:  profiles: order2
  
server:  port: 8202